### ISSUE TITLE
template custom_field_alarm_entity is missing

### ISSUE THREAD

**Issue by Ikari34** [fredrikpersson92/minihass#1]
Hi,
when I insert an alarm custom button-card I have an error : the custom_field_alarm_entity is missing
can you add this template please ?
Thank you for this nice dashboard

**Comment by drashish87** [comment]
Not sure if you have already checked. There is already a yaml file with that name available.
https://github.com/fredrikpersson92/minihass/tree/main/custom_cards/custom_card_security

**Comment by Ikari34** [comment]
> Not sure if you have already checked. There is already a yaml file with that name available. https://github.com/fredrikpersson92/minihass/tree/main/custom_cards/custom_card_security

OUps Sorry I haven't seen it.
Thank you
