### ISSUE TITLE
Weather card

### ISSUE THREAD

**Issue by nagtegaal** [fredrikpersson92/minihass#13]
Could you please share the code for your little blue-ish weather card? It looks amazing, and I would like to see how you managed to display multiple entities inside one card.

Thanks in advance

**Comment by fredrikpersson92** [comment]
Hey, unfortunately I don't have that exact version of the card saved. I'm trying to make a better design. But I will for sure post when I have something. Glad you like it!

**Comment by nagtegaal** [comment]
Another example of how to display multiple entities/icons within a card, would also be good..
I'm trying to understand how that simply works, but I'm unsure how to proceed.

Could you give an example of such a card?

**Comment by fredrikpersson92** [comment]
All my card are using custom button card. The display more than just the ordinare name, label, state and icon you use the custom_fields. A custom_field can be anythin. From just plain rich text, to a template to another card.
