### ISSUE TITLE
Round buttons

### ISSUE THREAD

**Issue by off112a** [fredrikpersson92/minihass#14]
Hi,

Could you share the code for the round buttons?

![272816975-5b3fd949-3a2f-406e-904b-17997335c291](https://github.com/fredrikpersson92/minihass/assets/22722009/514ef8e8-143d-43bd-9fe4-2858d1deafb1)

**Comment by fredrikpersson92** [comment]
Hi, please see the updated version of this card:
https://github.com/fredrikpersson92/minihass/tree/main/custom_cards/custom_card_scene
