### ISSUE TITLE
Issues with the new scene card

### ISSUE THREAD

**Issue by damianeickhoff** [fredrikpersson92/minihass#19]
I've tested the new scene card and found 2 issues with it. Both probably have to do with a "outdated" theme file.

- The fontsize `fs-800-resp` does not exist in the currently uploaded theme file
- the `rgba(var(--<color>),.<opacity>` does not work. I guess its because the `var` is translated to the full `value`, so for white it would be `rgb(255,255,255)` which will result in `rgba(rgb(255,255,255),.55)` which won't work.

**Comment by fredrikpersson92** [comment]
Correct, that is my the readme says to change font size and colors :)
