### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by chrisdevh** [fredrikpersson92/minihass#2]
Hey, I saw your dashboard at the Everything Smart Home Channel and luckly found github name in the comment section. I just wanted to say, thank you very much for sharing the code. This just looks awesome. After a litte configuration work in my dashboard I finally got it up and running, togehter with another UI configured dashboard. 

I really looking forward for our other layouts if you will share them? 

Would you mind, that I open a PR to enhance your readme to have a more enhanced explaination how to configure it to get it up and running?

**Comment by fredrikpersson92** [comment]
Hi, thanks and glad you like it! :)
Do you mean Pull Request? This is all very new to me still so not sure what to do next, but by all means, if you can help others then go ahead!

I am constantly updating my own cards, so if there is a process other than just overwriting the cards I ahve allready uploaded here then please let me know.

**Comment by marvandorth** [comment]
I think what @chrisdevh also means is all the other aspects / cards of your dashboard as showcased on ESH's channel.
Perhaps you'd be able to share your button_card_templates file so we can figure out the rest of your awsesome dashboard!

**Comment by fredrikpersson92** [comment]
Hi, yeah I posting the templates for each card as I have time to prepare them and whenI feel they are “ready enough” :)

**Comment by marvandorth** [comment]
> Hi, yeah I posting the templates for each card as I have time to prepare them and whenI feel they are “ready enough” :)
> […](#)
> On 20 Oct 2023, 10:25 +0200, marvandorth ***@***.***>, wrote: I think what @chrisdevh also means is all the other aspects / cards of your dashboard as showcased on ESH's channel. Perhaps you'd be able to share your button_card_templates file so we can figure out the rest of your awsesome dashboard! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I see! No hurry. I'll be waiting patiently :)

**Comment by chrisdevh** [comment]
@marvandorth: Yes you are correct, there are so much more cool things to integrate, like the water card, equalizer, music etc and even the headline of the dashbord and how to hide the general bar in the HA App. 

@fredrikpersson92: I'll wait as well. IMHO: You cards are already near to perfect and good looking. And yes, by PR I mean a pull-request. I will try to write the update in the evening and make the PR.

In general and maybe longterm goal, this will be provided as HACS integration?

**Comment by Akeyzerr** [comment]
I'm game to help with whatever I can :) These dashboard elements are awesome!

**Comment by chrisdevh** [comment]
@fredrikpersson92 As promised the PR https://github.com/fredrikpersson92/minihass/pull/3 for you to review and approve/modify or decline it as you like. Hope that helps.
