### ISSUE TITLE
Security navigation button

### ISSUE THREAD

**Issue by off112a** [fredrikpersson92/minihass#8]
Hi, 

really beautiful dashboard. 

But I wonder how to do this card:

![minihass](https://github.com/fredrikpersson92/minihass/assets/22722009/d054e9ea-e2f7-4e64-a0d1-37b4e41647ce)

**Comment by fredrikpersson92** [comment]
Thank you! I'm using a custom_filed to display another button card inside the first one.

**Comment by off112a** [comment]
Ok,
could you share the code?

**Comment by fredrikpersson92** [comment]
I've uploaded it here now:
https://github.com/fredrikpersson92/minihass/blob/main/custom_cards/custom_card_navigate/dashboard_alarm.yaml

**Comment by off112a** [comment]
Thank you 🙂
