### ISSUE TITLE
I permanetly get this issue

### ISSUE THREAD

**Issue by Itsememario** [fredrikpersson92/minihass#9]
**This is the issue:**

Konfiguration fehlerhaft!  ~Translation: Config Wrong / Config Not right (Homeassistant Config Checker)
Integration error: dashboards - Integration 'dashboards' not found.

also it wont work :( Can you help me? -Charged

**Comment by fredrikpersson92** [comment]
Can you share some screenshots of your setup?

**Comment by Itsememario** [comment]
Oki

**Comment by Itsememario** [comment]
oop it was hass issue i restarted the server full it works now but please dont close this yet

**Comment by Itsememario** [comment]
as im not finished with the dash

**Comment by fredrikpersson92** [comment]
sure thing:)

**Comment by Itsememario** [comment]
![image](https://github.com/fredrikpersson92/minihass/assets/90069597/4c5f5961-efab-46f2-9a0f-b7ccbfb2494b)

**Comment by Itsememario** [comment]
hmm

**Comment by fredrikpersson92** [comment]
Did you add the template to your dashboard config? If you using the GUI editor, it is in the top right corner.
If you are unsure how to do this, please check the documentation for custom button card.

**Comment by Itsememario** [comment]
> Did you add the template to your dashboard config? If you using the GUI editor, it is in the top right corner. If you are unsure how to do this, please check the documentation for custom button card.

I dont really know what you mean

**Comment by Itsememario** [comment]
mean this heree?

**Comment by fredrikpersson92** [comment]
Are you doing a yaml dashboard, or are you using the standard dashboard editor?

**Comment by Itsememario** [comment]
yaml

**Comment by Itsememario** [comment]
![image](https://github.com/fredrikpersson92/minihass/assets/90069597/512a9a3a-278f-47f2-a4fd-f386dfa6df06)

**Comment by Itsememario** [comment]
Btw we can keep chatting i am in front of pc i will reply instantly

**Comment by fredrikpersson92** [comment]
I suggest looking at the setup guide for UI Minimalist if you do not understand mine. I can try to help but I'm really not that experienced. There are others who have described the steps much better.

Did you create a folder named ui_lovelace_minihass? That is where you also add a folder for the templates. In that folder, you add my templates. The .yaml files

![Uploading Screenshot 2023-11-08 at 19.36.16.png…]()

**Comment by fredrikpersson92** [comment]
<img width="948" alt="Screenshot 2023-11-08 at 19 36 16" src="https://github.com/fredrikpersson92/minihass/assets/105781178/46e6cf6e-7489-42e8-b0e3-0eccd933652d">

**Comment by Itsememario** [comment]
wait 1 sec

**Comment by Itsememario** [comment]
i think i found an issue oops

**Comment by fredrikpersson92** [comment]
btw, I realy suggest you download VS Code form Hacs if you are to work in yaml

**Comment by Itsememario** [comment]
ok thx

**Comment by Itsememario** [comment]
doing it rn

**Comment by marvandorth** [comment]
Guys... Perhaps it's better to move to dm's for this kind of conversation.
It's annoying to receive an email for every sentence written...

**Comment by Itsememario** [comment]
XD

**Comment by Itsememario** [comment]
ok dc maybe?

**Comment by fredrikpersson92** [comment]
Discord? fredrik_persson_

**Comment by Itsememario** [comment]
request send once accepted this converstion will be closed and i will discuss privatly

**Comment by Itsememario** [comment]
**_This is now closed._**
